//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geonorge.Validator.Application.Rules.GenericGml.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class gml_xlink_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal gml_xlink_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geonorge.Validator.Application.Rules.GenericGml.Translations.gml.xlink.1", typeof(gml_xlink_1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fungerende og gyldige referanser mellom objekter og til eksterne kodelisteverdier..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Elementet mangler referanse..
        /// </summary>
        internal static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referansen til kodelisten &apos;{0}&apos; mangler fragment..
        /// </summary>
        internal static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finne kodelisten &apos;{0}&apos; ({1})..
        /// </summary>
        internal static string Message3 {
            get {
                return ResourceManager.GetString("Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodelisten &apos;{0}&apos; er utilgjengelig ({1})..
        /// </summary>
        internal static string Message4 {
            get {
                return ResourceManager.GetString("Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressursen &apos;{0}&apos; er en ugyldig kodeliste..
        /// </summary>
        internal static string Message5 {
            get {
                return ResourceManager.GetString("Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdien &apos;{0}&apos; finnes ikke i kodelisten &apos;{1}&apos;..
        /// </summary>
        internal static string Message6 {
            get {
                return ResourceManager.GetString("Message6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referansen fra {0} til {1} &apos;{2}&apos; har ugyldig format..
        /// </summary>
        internal static string Message7 {
            get {
                return ResourceManager.GetString("Message7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referansen fra {0} til {1} &apos;{2}&apos; fungerer ikke..
        /// </summary>
        internal static string Message8 {
            get {
                return ResourceManager.GetString("Message8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referansen fra {0} til {1} &apos;{2}&apos; er ugyldig. Gyldige objekttyper er: {3}..
        /// </summary>
        internal static string Message9 {
            get {
                return ResourceManager.GetString("Message9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fungerende referanser.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
    }
}
